### ISSUE TITLE
Could not spawn casa instance

### ISSUE THREAD

**Issue by tammojan** [apertif/apercal#191]
Casa call timed out on happili-02:
```
03/20/2019 12:09:35 AM - apercal.modules.preflag - DEBUG : Flagging subband edges for target beam 10
03/20/2019 12:09:35 AM - drivecasa.interface - DEBUG : Starting casa with flags:
03/20/2019 12:09:35 AM - drivecasa.interface - DEBUG : --nologger --nogui --colors=NoColor --log2term
03/20/2019 12:10:35 AM - drivecasa.interface - WARNING : 1 CASA spawning timeouts occurred.
03/20/2019 12:11:35 AM - drivecasa.interface - WARNING : 2 CASA spawning timeouts occurred.
03/20/2019 12:12:35 AM - drivecasa.interface - WARNING : 3 CASA spawning timeouts occurred.
03/20/2019 12:12:35 AM - apercal.pipeline.start_pipeline - ERROR : Apercal threw an error after 1:25:59.693251
Traceback (most recent call last):
  File "/home/apercal/apercal/apercal/pipeline/start_pipeline.py", line 217, in start_apercal_pipeline
    p1.go()
  File "/home/apercal/apercal/apercal/modules/preflag.py", line 101, in go
    self.edges()
  File "/home/apercal/apercal/apercal/modules/preflag.py", line 265, in edges
    lib.run_casa([tg_edges_flagcmd])
  File "/home/apercal/apercal/apercal/libs/lib.py", line 146, in run_casa
    casa = drivecasa.Casapy()
  File "/home/apercal/pipeline/local/lib/python2.7/site-packages/drivecasa/interface.py", line 155, in __init__
    raise RuntimeError("Could not spawn CASA instance")
RuntimeError: Could not spawn CASA instance
```

**Comment by tammojan** [comment]
I'm ignoring this for now, after a restart it didn't happen again. This is one of the things why we need to keep an eye on running pipelines. For now.
