### ISSUE TITLE
add scal CWL step

### ISSUE THREAD

**Issue by gijzelaerr** [apertif/apercal#200]

**Comment by gijzelaerr** [comment]
The SCAL CWL step is currently implemented, but fails with this error:
```

INFO:apercal.modules.scal:Starting SELF CALIBRATION
DEBUG:apercal.subs.managefiles:Creating directory 00/selfcal #
DEBUG:apercal.subs.managefiles:Moved to directory 00/selfcal #
INFO:apercal.modules.scal:Beam 00: Averaging data to one channel per subband for self-calibration
ERROR:apercal.modules.scal:Beam 00: Converted dataset not available
DEBUG:apercal.subs.managefiles:Creating directory 00/selfcal #
DEBUG:apercal.subs.managefiles:Moved to directory 00/selfcal #
INFO:apercal.modules.scal:Beam 00: Automatically flagging HI-line/RFI
DEBUG:masher:invert map=map slop=1 beam=beam stokes=i cell=5 vis=/dUrtnC/NGC807.mir imsize=1024 
DEBUG:basher:invert map=map slop=1 beam=beam stokes=i cell=5 vis=/dUrtnC/NGC807.mir imsize=1024 
DEBUG:basher:Command = invert map=map slop=1 beam=beam stokes=i cell=5 vis=/dUrtnC/NGC807.mir imsize=1024 
DEBUG:basher:

invert: Revision 1.23, 2017/07/27 05:46:17 UTC

Reading the visibility data ...
Making cubes with 16384 planes
Visibilities accepted: 132
Sidelobe suppression area is 5120x5120 arcsec
 ... this corresponds to uniform weighting
Calculating the weights ...
Applying the weights ...
Theoretical rms noise: 2.137E-02
Forming the beam ...
Forming Stokes I  image ...

DEBUG:basher:### Informational:  Using uniform weighting with robust unset is not recommended
### Warning:  Number of channels with no good data: 1688
### Warning:  Error allocating space for image
### Fatal Error:  Input/output error

Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/scal.py", line 115, in go
    self.flagline()
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/scal.py", line 199, in flagline
    invert.go()
  File "/usr/local/lib/python2.7/dist-packages/apercal/libs/lib.py", line 387, in go
    output = masher(**self.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/apercal/libs/lib.py", line 202, in masher
    out = basher(cmd, showasinfo=False)
  File "/usr/local/lib/python2.7/dist-packages/apercal/libs/lib.py", line 276, in basher
    raise RuntimeError("Error in command " + cmd.split(" ")[0] + ": \n" + err)
RuntimeError: Error in command invert: 
### Informational:  Using uniform weighting with robust unset is not recommended
### Warning:  Number of channels with no good data: 1688
### Warning:  Error allocating space for image
### Fatal Error:  Input/output error

[job scal.cwl] Max memory used: 27660MiB
[job scal.cwl] completed permanentFail
```

**Comment by gijzelaerr** [comment]
was already implemented
