### ISSUE TITLE
Add subdirification condition around extra plaatjes in flagging step

### ISSUE THREAD

**Issue by gijzelaerr** [apertif/apercal#203]
When preflagging is ran inside container/CWL it fails:
```
DEBUG:basher:Returning output.
DEBUG:apercal.modules.preflag:Used AOFlagger to flag flux calibrator with preliminary bandpass applied
INFO:apercal.modules.preflag:Storing flagging images for /qLuBPt/3C295.MS
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/preflag.py", line 94, in go
    self.aoflagger()
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/preflag.py", line 396, in aoflagger
    self.aoflagger_flag()
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/preflag.py", line 1069, in aoflagger_flag
    self.aoflagger_plot(self.get_fluxcal_path())
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/preflag.py", line 1016, in aoflagger_plot
    os.makedirs(destination_path)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/qa'
[job preflag.cwl] Max memory used: 118361MiB
[job preflag.cwl] completed permanentFail
```
A check needs to be added if subdirification is enabled or not.

**Comment by gijzelaerr** [comment]
merged!
