### ISSUE TITLE
problem running casa inside container

### ISSUE THREAD

**Issue by gijzelaerr** [apertif/apercal#43]
```
/usr/bin/make -f /home/gijs/Work/apercal/Makefile run
/home/gijs/Work/apercal/.venv2/bin/cwltool --enable-ext --outdir=cwl/outdir cwl/apercal.cwl cwl/job.yaml
/home/gijs/Work/apercal/.venv2/bin/cwltool 1.0.20180820141117
Resolved 'cwl/apercal.cwl' to 'file:///home/gijs/Work/apercal/cwl/apercal.cwl'
[workflow ] start
[workflow ] starting step preflag
[step preflag] start
[job preflag] /tmp/tmpKgCydq$ docker \
    run \
    -i \
    --volume=/tmp/tmpKgCydq:/var/spool/cwl:rw \
    --volume=/tmp/tmpIwhn1W:/tmp:rw \
    --volume=/home/gijs/Work/apercal/data/small/00/raw/3C295.MS:/var/lib/cwl/stgef4bb83d-9ce5-4290-bf0d-3663e229f9ce/3C295.MS:ro \
    --volume=/home/gijs/Work/apercal/data/small/00/raw/3C138.MS:/var/lib/cwl/stga885b5e0-6595-417b-b24f-58d8970ae663/3C138.MS:ro \
    --volume=/home/gijs/Work/apercal/data/small/00/raw/NGC807.MS:/var/spool/cwl/NGC807.MS:rw \
    --workdir=/var/spool/cwl \
    --read-only=true \
    --user=1000:1000 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/var/spool/cwl \
    apertif/apercal \
    python \
    -c \
    'import logging
logging.basicConfig(level=logging.INFO)
from apercal.modules.preflag import preflag
from os import getcwd

p = preflag()
p.target = "/var/spool/cwl/NGC807.MS"
p.fluxcal = "/var/lib/cwl/stgef4bb83d-9ce5-4290-bf0d-3663e229f9ce/3C295.MS"
p.polcal = "/var/lib/cwl/stga885b5e0-6595-417b-b24f-58d8970ae663/3C138.MS"
p.subdirification = False
p.go()'
INFO:apercal.libs.lib: No configuration file given or file not found, using default values.
INFO:apercal.modules.preflag:Starting Pre-flagging step
INFO:apercal.modules.preflag:Flagging shadowed antennas
INFO:apercal.modules.preflag:Flagging subband edges
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/preflag.py", line 110, in go
    self.edges()
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/preflag.py", line 242, in edges
    casa.run_script(casacmd_fcflag, raise_on_severe=True, timeout=1800)
  File "/usr/local/lib/python2.7/dist-packages/drivecasa/interface.py", line 216, in run_script
    e.message)
RuntimeError: Casapy encountered a 'SEVERE' level problem running the command flagdata(vis="/var/lib/cwl/stgef4bb83d-9ce5-4290-bf0d-3663e229f9ce/3C295.MS", spw="0:0;64;128;192;256;320;384;448;512;576;640;704;768;832;896;960;1024;1088;1152;1216;1280;1344;1408;1472;1536;1600;1664;1728;1792;1856;1920;1984;2048;2112;2176;2240;2304;2368;2432;2496;2560;2624;2688;2752;2816;2880;2944;3008;3072;3136;3200;3264;3328;3392;3456;3520;3584;3648;3712;3776;3840;3904;3968;4032;4096;4160;4224;4288;4352;4416;4480;4544;4608;4672;4736;4800;4864;4928;4992;5056;5120;5184;5248;5312;5376;5440;5504;5568;5632;5696;5760;5824;5888;5952;6016;6080;6144;6208;6272;6336;6400;6464;6528;6592;6656;6720;6784;6848;6912;6976;7040;7104;7168;7232;7296;7360;7424;7488;7552;7616;7680;7744;7808;7872;7936;8000;8064;8128;8192;8256;8320;8384;8448;8512;8576;8640;8704;8768;8832;8896;8960;9024;9088;9152;9216;9280;9344;9408;9472;9536;9600;9664;9728;9792;9856;9920;9984;10048;10112;10176;10240;10304;10368;10432;10496;10560;10624;10688;10752;10816;10880;10944;11008;11072;11136;11200;11264;11328;11392;11456;11520;11584;11648;11712;11776;11840;11904;11968;12032;12096;12160;12224;12288;12352;12416;12480;12544;12608;12672;12736;12800;12864;12928;12992;13056;13120;13184;13248;13312;13376;13440;13504;13568;13632;13696;13760;13824;13888;13952;14016;14080;14144;14208;14272;14336;14400;14464;14528;14592;14656;14720;14784;14848;14912;14976;15040;15104;15168;15232;15296;15360;15424;15488;15552;15616;15680;15744;15808;15872;15936;16000;16064;16128;16192;16256;16320;1;65;129;193;257;321;385;449;513;577;641;705;769;833;897;961;1025;1089;1153;1217;1281;1345;1409;1473;1537;1601;1665;1729;1793;1857;1921;1985;2049;2113;2177;2241;2305;2369;2433;2497;2561;2625;2689;2753;2817;2881;2945;3009;3073;3137;3201;3265;3329;3393;3457;3521;3585;3649;3713;3777;3841;3905;3969;4033;4097;4161;4225;4289;4353;4417;4481;4545;4609;4673;4737;4801;4865;4929;4993;5057;5121;5185;5249;5313;5377;5441;5505;5569;5633;5697;5761;5825;5889;5953;6017;6081;6145;6209;6273;6337;6401;6465;6529;6593;6657;6721;6785;6849;6913;6977;7041;7105;7169;7233;7297;7361;7425;7489;7553;7617;7681;7745;7809;7873;7937;8001;8065;8129;8193;8257;8321;8385;8449;8513;8577;8641;8705;8769;8833;8897;8961;9025;9089;9153;9217;9281;9345;9409;9473;9537;9601;9665;9729;9793;9857;9921;9985;10049;10113;10177;10241;10305;10369;10433;10497;10561;10625;10689;10753;10817;10881;10945;11009;11073;11137;11201;11265;11329;11393;11457;11521;11585;11649;11713;11777;11841;11905;11969;12033;12097;12161;12225;12289;12353;12417;12481;12545;12609;12673;12737;12801;12865;12929;12993;13057;13121;13185;13249;13313;13377;13441;13505;13569;13633;13697;13761;13825;13889;13953;14017;14081;14145;14209;14273;14337;14401;14465;14529;14593;14657;14721;14785;14849;14913;14977;15041;15105;15169;15233;15297;15361;15425;15489;15553;15617;15681;15745;15809;15873;15937;16001;16065;16129;16193;16257;16321;63;127;191;255;319;383;447;511;575;639;703;767;831;895;959;1023;1087;1151;1215;1279;1343;1407;1471;1535;1599;1663;1727;1791;1855;1919;1983;2047;2111;2175;2239;2303;2367;2431;2495;2559;2623;2687;2751;2815;2879;2943;3007;3071;3135;3199;3263;3327;3391;3455;3519;3583;3647;3711;3775;3839;3903;3967;4031;4095;4159;4223;4287;4351;4415;4479;4543;4607;4671;4735;4799;4863;4927;4991;5055;5119;5183;5247;5311;5375;5439;5503;5567;5631;5695;5759;5823;5887;5951;6015;6079;6143;6207;6271;6335;6399;6463;6527;6591;6655;6719;6783;6847;6911;6975;7039;7103;7167;7231;7295;7359;7423;7487;7551;7615;7679;7743;7807;7871;7935;7999;8063;8127;8191;8255;8319;8383;8447;8511;8575;8639;8703;8767;8831;8895;8959;9023;9087;9151;9215;9279;9343;9407;9471;9535;9599;9663;9727;9791;9855;9919;9983;10047;10111;10175;10239;10303;10367;10431;10495;10559;10623;10687;10751;10815;10879;10943;11007;11071;11135;11199;11263;11327;11391;11455;11519;11583;11647;11711;11775;11839;11903;11967;12031;12095;12159;12223;12287;12351;12415;12479;12543;12607;12671;12735;12799;12863;12927;12991;13055;13119;13183;13247;13311;13375;13439;13503;13567;13631;13695;13759;13823;13887;13951;14015;14079;14143;14207;14271;14335;14399;14463;14527;14591;14655;14719;14783;14847;14911;14975;15039;15103;15167;15231;15295;15359;15423;15487;15551;15615;15679;15743;15807;15871;15935;15999;16063;16127;16191;16255;16319;16383", flagbackup=False)
Error message is as follows:
Casapy encountered a 'SEVERE' level problem running the script at /tmp/tmp7jg75y: 
*********

*********
Errors are as follows:
2018-11-02 13:28:46	SEVERE	agentflagger:: (file ../../tools/flagging/agentflagger_cmpt.cc, line 39)	Exception Reported: Column FLAG in table /tmp/drivecasa/tab282_2 is not writable
2018-11-02 13:28:46	SEVERE	flagdata::::	Column FLAG in table /tmp/drivecasa/tab282_2 is not writable
[job preflag] completed permanentFail
[step preflag] completed permanentFail
[workflow ] completed permanentFail```

**Comment by gijzelaerr** [comment]
running cwltool with `--no-match-user` doesn't seem to help
