### ISSUE TITLE
preflag test fails on test data

### ISSUE THREAD

**Issue by gijzelaerr** [apertif/apercal#60]
```
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/preflag.py", line 110, in go
    self.edges()
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/preflag.py", line 280, in edges
    nchannel = self._getnchan(vis)
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/preflag.py", line 119, in _getnchan
    spectralwindowtable = pt.table(msname + '::SPECTRAL_WINDOW', ack=False)
  File "/usr/lib/python2.7/dist-packages/casacore/tables/table.py", line 363, in __init__
    Table.__init__(self, tabname, lockopt, opt)
RuntimeError: Table /var/spool/cwl/NGC807.MS::SPECTRAL_WINDOW does not exist (subtable SPECTRAL_WINDOW is unknown)
```

**Comment by gijzelaerr** [comment]
this has been solved with the new test data
