### ISSUE TITLE
Can run preflag test only once

### ISSUE THREAD

**Issue by gijzelaerr** [apertif/apercal#67]
for the second run it gives
```
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/preflag.py", line 83, in go
    self.edges()
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/preflag.py", line 243, in edges
    nchannel = self._getnchan(vis)
  File "/usr/local/lib/python2.7/dist-packages/apercal/modules/preflag.py", line 92, in _getnchan
    spectralwindowtable = pt.table(msname + '::SPECTRAL_WINDOW', ack=False)
  File "/usr/lib/python2.7/dist-packages/casacore/tables/table.py", line 363, in __init__
    Table.__init__(self, tabname, lockopt, opt)
RuntimeError: Table /var/spool/cwl/NGC807.MS::SPECTRAL_WINDOW does not exist (subtable SPECTRAL_WINDOW is unknown)
```

**Comment by gijzelaerr** [comment]
one way to solve this is to copy the data to a temporary folder and do the processing there, followed by a delete. I think it is important to make sure that tests don't have side effects anyway.
